### ISSUE TITLE
Add documentation on how to test state expiration from a rust test

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#426]
### What problem does your feature solve?
Guidance on unit test, adding an example, that bumps the ledger sequence to test state expriation

```[tasklist]
### Tasks
- [x] Describe test setup
- [x] Create an example that bumps the ledger sequence
- [x] Describe expected errors
```

**Comment by leighmcculloch** [comment]
This is a follow up of:
- https://github.com/stellar/rs-soroban-sdk/issues/1162

**Comment by dmkozh** [comment]
Added guide in https://github.com/stellar/stellar-docs/pull/630

**Comment by janewang** [comment]
Thank you so much @dmkozh!
