### ISSUE TITLE
getLedgerEntries: add meaningful coding examples

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-docs#469]
The `getLedgerEntries` method is pretty powerful, you can retrieve any piece of state from the ledger: accounts, trustlines, offers, data, liquidity pools, contract wasms, contract instances, contract storage, yada yada.

However, there are two challenges associated with that: 
1. building the relevant xdr key for the type of ledger entry you're looking for
2. parsing the xdr result

However, our coding examples use pre-built keys and don't parse the results. I think that modifying our JS and Python examples in this page to include these can help unlock human potential

```[tasklist]
### Tasks
- [x] Add a full list of keys and description for each key
- [x] Add examples for how to use the keys to retrieve accounts and balances
- [x] Add examples for how to use the keys to retrieve trustlines
- [x] Add examples for how to use the keys to retrieve contract wasms
- [x] Add examples for how to use the keys to retreive contract state / storage
- [x] Add examples for how to use the keys to retrieve contract instances
```
