### ISSUE TITLE
soroban-by-example.org

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-docs#477]
Placeholder issue for building ???-by-example.com website to teach new devs how to write stellar contracts.
Inspired by: https://solidity-by-example.org, and https://gobyexample.com. Largely, this depends on a lot of example contracts, building up from hello world, to complex defi examples.

## TODO
- [ ] Figure out a name/domain
- [ ] Create a repo for that and convert these to issues there.
- [ ] Plan the different examples and how they fit together
- [ ] Start writing example contracts
  - Paul: IMO, it would be nice to follow a "jupyter-notebook" or "literate code" style here where we have snippets of code, with lots of explainer text and examples mixed in.
- [ ] Make the code runnable "live" in-line in the browser 🤯 
  - See: https://github.com/paulbellamy/rs-stellar-wasm-browser

**Comment by janewang** [comment]
http://soroban-by-example.com currently redirects to soroban examples

**Comment by koolamusic** [comment]
My team built sorobanexamples.xyz and have the opensource repo at https://github.com/daccred

We took most of our inspiration from the ecosystem and integrated an AI agent that can extend an existing example contract with new functionality
