### ISSUE TITLE
Epic - Testing

### ISSUE THREAD

**Issue by anataliocs** [stellar/stellar-docs#973]
```[tasklist]
### Tasks
- [ ] Add Unit testing
- [ ] Add Integration testing
- [ ] Add static analysis
- [ ] Create test environment for manual QA
```
